# Service Manifest file for frontend Angular Application 
apiVersion: v1
kind: Service
metadata:
  name: chat-app-be-svc-ci
spec:
  selector:
    app: chat-app-backend
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 3001
    # If you modify this nodePort, ensure that you also update the CORS_ORIGIN_URL in the dotnet-deploy manifest.
  type: ClusterIP